// <auto-generated />
using System;
using IslamicSearch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IslamicSearch.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180823075920_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("IslamicSearch.Models.HadithModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("arabicHTML");

                    b.Property<string>("arabicText");

                    b.Property<string>("englishHTML");

                    b.Property<string>("englishText");

                    b.Property<int?>("in_book_refrenceid");

                    b.Property<int>("number");

                    b.Property<int?>("old_refrenceid");

                    b.HasKey("id");

                    b.HasIndex("in_book_refrenceid");

                    b.HasIndex("old_refrenceid");

                    b.ToTable("HadithModel");
                });

            modelBuilder.Entity("IslamicSearch.Models.In_Book_Refrence", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("book");

                    b.Property<int>("hadith");

                    b.Property<string>("tag");

                    b.HasKey("id");

                    b.ToTable("In_Book_Refrence");
                });

            modelBuilder.Entity("IslamicSearch.Models.Old_refrence", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("book");

                    b.Property<int>("hadith");

                    b.Property<int>("vol");

                    b.HasKey("id");

                    b.ToTable("Old_refrence");
                });

            modelBuilder.Entity("IslamicSearch.Models.HadithModel", b =>
                {
                    b.HasOne("IslamicSearch.Models.In_Book_Refrence", "in_book_refrence")
                        .WithMany()
                        .HasForeignKey("in_book_refrenceid");

                    b.HasOne("IslamicSearch.Models.Old_refrence", "old_refrence")
                        .WithMany()
                        .HasForeignKey("old_refrenceid");
                });
#pragma warning restore 612, 618
        }
    }
}
